language: ruby

install:
  - bundle install --retry=3

addons:
  code_climate:
    repo_token: 2430641a7445196a1ad98e0372a7bf2d0b88998bdb754c77de1831f0eb03635d

rvm:
  - ruby-head
  - 2.1
  - 2.2
  - 2.0.0
  - 1.9.3
  - jruby-19mode